apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: kinesis-event-source
spec:
  template:
    spec:
      containers:
        - image: 771830474512.dkr.ecr.us-east-1.amazonaws.com/kinesis-knative-ingest:latest
          name: kinesis-knative-eventer
          env:
            - name: POD_NAME
              value: "kinesis-ingest"
            - name: POD_NAMESPACE
              value: "kinesis-knative-ingest"
            - name: DATA_STREAM
            # TODO: Inject the correct value here on deployment
              value: ""
          command: ["python3"]
          args: ["/app/ingest.py"]
              
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: video-sink